obj-y += main_page.o
obj-y += page_manag.o
obj-y += setting_page.o
obj-y += browse_page.o
obj-y += picture_page.o
obj-y += auto_page.o
obj-y += interval_page.o
obj-y += music_page.o
obj-y += text_page.o

